name: E2E Test Artemis

on:
  workflow_run:
    # Must match the name of build.yml workflow.
    workflows: ["Test Artemis"]
    types: [completed]

jobs:

  server-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: artemis-build/test-results/results.xml
